### ISSUE TITLE
EMG filtering fails if the analysis window is too big

### ISSUE THREAD

**Issue by cpizzolato** [RehabEngGroup/MOtoNMS#1]
During the filtering of EMGs, if the EMGOffest defined in the elaboration XML (`<EMGOffset>0.2</EMGOffset>`) exceeds the length of the trial an error is thrown and the elaboration is interrupted. In this case I think it would be better to give just a warning, and  instead selecting automatically  the maximum allowable EMG offset for the current trial. 

**Error report**

```
Error using selectionData (line 74)
----------------------------------------------------------------
WARNING: WRONG PARAMETERS SELECTION in the configuration file.
Analysis Window out of available data for trial 1.
PLEASE CHANGE method or frames of the analysis window for that trial in your configuration file and
TRY again.
----------------------------------------------------------------

Error in runDataProcessing (line 391)
        [EMGsFiltered,EMGtime]=selectionData(EMGsEnvelope,AnalysisWindow,AnalogFrameRate,EMGOffset);

Error in ElaborationInterface (line 97)
                runDataProcessing(elaborationPaths{ne});
```

**Comment by alicemantoan** [comment]
I guess you tried to select one of the first frames of your trial 1 as the Analysis WIndow start frame.
An error is thrown if you select the first 0.2 sec, since the EMGOffset can not be applied. This is pointed out in the User Manual (Data Processing: elaborate your dynamic trials, Warnings). The user can set the EMGOffset to 0 if not interested in the use of EMG signals, or he/she must remember to not select the initial frames (according to the EMGOffset defined in the elaboration.xml and the VideoFrameRate of the acquisition). 
I think he/she must be aware of this constraint.
If a user selects the first frame, no EMGOffset is possible: I need to shift the Analysis Window selected by the user to be able to apply the settled EMGOffset (reasonably often different from 0). Or, alternatively, how can I define the maximum allowable EMG offset in such a case?
Intentionally, I handled the error message suggesting the user to change the Analysis Window. I think it's better to make the user understand why he/she has to modify the Analysis WIndow definition (or the EMGOffset), instead of hide the Analysis Window (or just EMG) selection process.
Maybe I can add to the error message the translation of the EMGOffset into frame according to the video frame rate, saying something like (e.g. EMGOffset=0.2 sec and VideoFrameRate=200Hz):
"Selection of first 40 frames is not possible due to the defined EMGOffset (i.e. 0.2 sec): please change the EMGOffset or the Analysis Window definition." 
If the problem is clear, I think it does not take so long to rerun the elaboration...
